num1 = int(input("请输入第一个数字"))
num2 = int(input("请输入第二个数字"))
num3 = int(input("请输入第三个数字"))
num4 = int(input("请输入第四个数字"))
num5 = int(input("请输入第五个数字"))
num6 = int(input("请输入第六个数字"))
num7 = int(input("请输入第七个数字"))
num8 = int(input("请输入第八个数字"))
num9 = int(input("请输入第九个数字"))
num10 = int(input("请输入第十个数字"))
print(num1+num2+num3+num4+num5+num6+num7+num8+num9+num10)